services:
  - type: web
    name: lab-inventory-web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: COOKIE_SECURE
        value: "1"
      - key: DEFAULT_ADMIN_USERNAME
        value: admin
      - key: DEFAULT_ADMIN_PASSWORD
        value: admin123456
      - key: DEFAULT_ADMIN_DISPLAY_NAME
        value: 系统管理员
